"""add password_hash

Revision ID: f312965db154
Revises: 0be38032ba3e
Create Date: 2025-10-20 01:04:17.935362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f312965db154'
down_revision: Union[str, Sequence[str], None] = '0be38032ba3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('properties', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('properties', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('properties', 'area_sqm',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.drop_constraint(op.f('properties_owner_id_fkey'), 'properties', type_='foreignkey')
    op.create_foreign_key(None, 'properties', 'users', ['owner_id'], ['id'])
    op.drop_column('properties', 'created_at')
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.add_column('properties', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.create_foreign_key(op.f('properties_owner_id_fkey'), 'properties', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.alter_column('properties', 'area_sqm',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('properties', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('properties', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('properties', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
